global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'freeswitch-pbx'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # NestJS Application (running in Docker)
  - job_name: 'nestjs-api'
    static_configs:
      - targets: ['nestjs-api:3000']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # RabbitMQ Message Queue
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # FreeSWITCH (if metrics exporter is available)
  - job_name: 'freeswitch'
    static_configs:
      - targets: ['freeswitch:9194']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom application metrics (duplicate - removed)
  # - job_name: 'pbx-metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:3000']
  #   scrape_interval: 15s
  #   metrics_path: /api/v1/metrics
  #   scrape_timeout: 10s
